#!/usr/bin/python
"""Split members of workspace into evenly sized chunks for testing

Example splitting members into three chunks:

# Test first of three chunks
$ ./split_workspace 1 3  # rewrites Cargo.toml
$ cargo test

# Reset Cargo.toml and test second of three chunks
$ git checkout Cargo.toml
$ ./split_workspace 2 3
$ cargo test

# Reset Cargo.toml and test third of three chunks
$ git checkout Cargo.toml
$ ./split_workspace 3 3
$ cargo test
"""

import sys
import toml


def get_chunk(members, part, total_parts):
   chunk_size = int(len(members) / total_parts)
   end = None if part == total_parts - 1 else chunk_size*(part+1)
   return members[chunk_size*part:end]


def main():
    if len(sys.argv) != 3:
        raise AssertionError('Expected exactly two arguments')
    part, total_parts = int(sys.argv[1]) - 1, int(sys.argv[2])
    content = toml.load('Cargo.toml')
    members_of_part = get_chunk(content['workspace']['members'], part, total_parts)
    content['workspace']['members'] = members_of_part
    with open('Cargo.toml', 'w') as f:
        toml.dump(content, f)


if __name__ == '__main__':
    main()
